version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microanalytics
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    command: uvicorn backend.api:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/microanalytics
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db_data:
